# Generated by Django 5.2 on 2025-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn_text', models.TextField()),
                ('date', models.DateTimeField()),
                ('player_1', models.CharField(max_length=100)),
                ('player_2', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
